[project]
name = "plantpassport"
version = "0.1.0"
description = "Plant Passport"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pymupdf>=1.26.3", "supabase>=2.18.1"]

[dependency-groups]
dev = ["ruff>=0.12.10"]
